In [3]:
import numpy as np

In [4]:
lst = [1,2,3,4]


arr = np.array(lst)

In [5]:
arr = np.random.randint(1,10,(3,4))

In [6]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,4))
arr

array([[9, 4, 9, 9],
       [1, 6, 4, 6],
       [8, 7, 1, 5]])

In [31]:
arr.flatten()

array([9, 4, 9, 9, 1, 6, 4, 6, 8, 7, 1, 5])

In [32]:
arr.reshape((3,4))

array([[9, 4, 9, 9],
       [1, 6, 4, 6],
       [8, 7, 1, 5]])

In [9]:
np.random.seed(4)
arr1 = np.random.randint(1,10,(4,3))
arr1

array([[8, 6, 2],
       [9, 8, 9],
       [3, 8, 8],
       [8, 9, 5]])

In [10]:
arr.dot(arr1)

array([[207, 239, 171],
       [122, 140, 118],
       [170, 157, 112]])

## mean variance standard deviation

In [33]:
arr= np.random.randint(1,20,(3,4))
arr

array([[13,  8, 15, 18],
       [ 3,  3,  2,  6],
       [ 9, 15,  2, 11]])

In [37]:
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

8.75
29.354166666666668
5.417948566262573
